version: '3.8'
services:
  tts:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=tts_models/en/ljspeech/tacotron2-DDC
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3